# Generated by Django 5.1.1 on 2024-10-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_coin_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='api_key',
            field=models.CharField(default='bitcoin', max_length=100),
            preserve_default=False,
        ),
    ]
