# Generated by Django 5.1.1 on 2024-10-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_coin_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='coin',
            field=models.ManyToManyField(related_name='watchlists', to='main_app.coin'),
        ),
    ]
