# Generated by Django 5.1.1 on 2024-10-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_watchlist_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='coin',
            field=models.ManyToManyField(related_name='watchlist', to='main_app.coin'),
        ),
    ]
